name: Running tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  code-checks-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for Permission Changes
        run: |
          if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
            BASE_REF=HEAD~1
          else
            BASE_REF=$(git merge-base HEAD origin/main 2>/dev/null || echo "HEAD")
          fi

          if git diff --name-only --diff-filter=X $BASE_REF HEAD | grep .; then
            echo "Permission changes detected!"
            exit 1
          else
            echo "No permission changes."
          fi

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install dependencies from pyproject.toml
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Ruff Linting
        run: |
          pip install ruff
          ruff check leakpro --exclude examples,leakpro/tests

      - name: Install PDF compiling tool
        run: |
          sudo apt update ; sudo apt install -y texlive-latex-base

      - name: Install pytest and pytest-cov
        run: |
          pip install pytest pytest-cov pytest-mock coverage-badge

      - name: Run tests with pytest
        run: |
          pytest --cov=leakpro --cov-report=term-missing:skip-covered --cov-report=xml --cov-report=html leakpro/tests/
          cat ./coverage.xml

      - name: Create Coverage Badge
        run: |
          mkdir -p badges
          coverage-badge -o badges/coverage.svg -f

      - name: Deploy Coverage Badge to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: badges